#version del docker compose
version: '3.8'
#Los servicios que se van a correr, los contenedores
services:
#nombre del servicio
  mysqldb:
  #Imagen que se utilizra a la hora de crear el contenedor de este servicio
    image: mysql
    #referencia del archivo de las variables
    env_file: ./.env
    #las variables de entorno
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      #Puertos que se usaran, y se pueden modificar en el archivo de variables
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#segundo servicio a correr
  app:
  #Sera connstruido con el dockerfile direccionado a la misma carpeta del docker compose
    build: .
    #dependencia del servicio de la base de datos
    depends_on:
      - mysqldb
    links:
      - mysqldb
    #Puertos a usar, se modifican en el archivco de variables
    ports:
      - $process.env.NODE_LOCAL_PORT:$process.env.NODE_DOCKER_PORT